### ISSUE TITLE
Surface Bulldozing no longer works. Any one else?

### ISSUE THREAD

**Issue by Skryl0n** [yenyang/Better_Bulldozer#5]
Not sure if it's interference from other mods or not. Doubtful. I use Mod Manager.

Better Bulldozer's surface delete icon stopped working. Unable to click/select/bulldoze.

Tried uninstalling and re-installing. Now interface of BB has disappeared, only vanilla option.

Anyone else?

**Comment by yenyang** [comment]
You can try sending me log files: 
%AppData%..\LocalLow\Colossal Order\Cities Skylines II\player.log
%AppData%..\LocalLow\Colossal Order\Cities Skylines II\logs\Mods_Yenyang_Better_Bulldozer.log

**Comment by Skryl0n** [comment]
Thanks for the time your putting into your mods, they're amazing! Thank you!

Attached the logs in the comment above

**Comment by Skryl0n** [comment]
I used to do it manually, but now I let Mod Manager do its thing. I'll have try another uninstall/reinstall

**Comment by yenyang** [comment]
You're welcome. Glad you sorted it out.
